const WAITING = 1
const GETTED = 2
const CONSIDERING = 4
const GETTED_CONSIDERING = GETTED + CONSIDERING
const TINGING = 8

module.exports = {
  WAITING,
  GETTED,
  CONSIDERING,
  GETTED_CONSIDERING,
  TINGING
}
